version: '3'
services:

  front:
    build: .
    image: wonnex/frontend
    container_name: frontend
    ports: 
      - 4200:4200
    restart: always
    
  back:
    build: .
    image: wonnex/backend
    container_name: backend
    ports:
      - 8080:8080
    restart: always
    links: 
    - front




