# This is a basic workflow to help you get started with Actions

name: backend

# Controls when the workflow will run
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build_test_docker:
    
    runs-on: ubuntu-latest
    
    defaults:
     run:
       working-directory: 'web-back'
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build and test with Gradle
      run: ./gradlew build
      
    - name: Clean jar
      run: ./gradlew clean
      
    - name: Build jar
      run: ./gradlew booJar

    - name: Test
      run: ./gradlew test
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} 
        
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag wonnex/backend:latest .
    - name: Publish dockerimage to docker hub
      run: docker push wonnex/backend:latest
   


    
     # - name: Build & push image
      #  run: |
       #    echo "${{secrets.DOCKER_HUB_ACCESS_TOKEN}}" | docker login -u "wonnex" --password-stdin
       #    docker image build -t wonnex/backend:latest .
       #    docker push wonnex/backend:latest 
