# This is a basic workflow to help you get started with Actions

name: frontend

on:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_test_docker_front:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
          node-version: [16.x]
    
    defaults:
          run:
             working-directory: 'web-front/web-frontend'
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci 
    - name: Build
      run: npm run build
    - name: Test
      run: npm test --no-watch --no-progress
    
  
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} 
        
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag wonnex/frontend:latest .
    - name: Publish dockerimage to docker hub
      run: docker push wonnex/frontend:latest
     
